[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_pawn_shop = "CaCpQaHiHgymut7cP9Jj7UkJXZh25fTdZftLeycWuGPV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
